import 'package:flutter/material.dart';

const bluePrimary = Color(0xFF3F51B5);
const white = Colors.white;
const white80 = Color(0XFFf2f2f2);
const black = Colors.black;
const green = Colors.green;
const greenAccent = Colors.greenAccent;
const red = Colors.red;
const redAccent = Colors.redAccent;
const grey = Colors.grey;
const grey500 = Color(0XFF4E4949);
const blueGrey = Colors.blueGrey;
const teal = Colors.teal;
const blue = Colors.blue;
const blueAccent = Colors.blueAccent;
const indigo = Colors.indigo;
const indigoAccent = Colors.indigoAccent;
const orange = Colors.orange;
const orangeAccent = Colors.orangeAccent;
const background = Color(0xFF212121);
const transparent = Colors.transparent;
const scaffoldColr = Color(0xFFF5F7FA);
