name: micro_front_end_poc
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  animated_bottom_navigation_bar: ^1.3.3
  hugeicons: ^0.0.7
  haptic_feedback: ^0.5.1+1
  fl_chart: ^0.69.2
  carousel_slider: ^5.0.0
  web_socket_channel: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

#=================== Local Packages For Android======================
#  out_duty:
#    path: D:/projects/micro_apps/out_duty
#  leave:
#    path: D:\micros\leave
#  profile:
#    path: D:/projects/micro_apps/profile

  utility:
    path:  micros/utility
#  exp_claim:
#    path: D:/projects/micro_apps/exp_claim

  #=================== Local Packages For IOS ======================

#  out_duty:
#      path: /Users/vikrantghan/Documents/Projects/MicrofrontEnd/out_duty
#  leave:
#      path: /Users/vikrantghan/Documents/Projects/MicrofrontEnd/leave
#  profile:
#      path: /Users/vikrantghan/Documents/Projects/MicrofrontEnd/profile
#  utility:
#      path: /Users/vikrantghan/Documents/Projects/MicrofrontEnd/utility

#=================== Remote Packages======================

  out_duty:
    git:
      url: "https://github.com/Sagar7262880/out_duty.git"
      ref: main

  leave:
    git:
      url: "https://github.com/Sagar7262880/leave.git"
      ref: master
#  utility:
#    git:
#      url: "https://github.com/Sagar7262880/utility.git"
#      ref: main
  geo_fencing:
      git:
        url: "https://github.com/Sagar7262880/geo_fencing.git"
        ref: main
#  exp_claim:
#    git:
#      url: "https://github.com/Sagar7262880/exp_claim.git"
#      ref: main


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/success.json
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Poppins-Regular.ttf
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

