name: utility
description: "A new Flutter package project."
version: 0.0.1
environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  shared_preferences: ^2.3.3
  lottie: ^3.1.3
  flutter_typeahead: ^4.8.0
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  location: ^7.0.0
  dio: ^5.7.0
  hugeicons: ^0.0.7
#  month_picker_dialog: any
  month_picker_dialog: ^4.0.0
  file_picker: any # ^8.0.3
  image_picker: ^1.1.1
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.3
  image_cropper: ^7.0.5
  permission_handler: ^11.3.1
  google_maps_flutter: any
  flutter_polyline_points: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


